### ISSUE TITLE
bootstrap.css not generated

### ISSUE THREAD

**Issue by derkmdt** [htanjo/kss-node-template#14]
Hi Hiroyuki,

I need some help with the initial demo run :)
I did a "npm install" from the template directory. And followed that one up with "kss-node demo/src demo/dist --template template --css bootstrap.css" also tried "kss-node demo/src --template template" . Have no errors in the cli. But the "style.css" or "bootstrap.css" is not generated. This also happens when I run the original kss demo in the "node_modules" kss package. Any Idea? I have the latest version, also did a npm update. Thx!

**Comment by htanjo** [comment]
kss-node doesn't generate CSS from Less (or Sass).
Strictly speaking, kss-node had compilation feature in 1.x but now it doesn't. - https://github.com/kss-node/kss-node/issues/83

We have to compile CSS by ourselves if we need the generated CSS in the style guide.

```sh
$ lessc demo/src/bootstrap.less demo/dist/bootstrap.css
$ kss-node demo/src demo/dist --template template --css bootstrap.css
```

In this project, I'm planning to automate these tasks using [npm scripts](https://docs.npmjs.com/misc/scripts) or [gulp](http://gulpjs.com/).

**Comment by derkmdt** [comment]
Thx for the quick reply! Maybe add that to the README.md :)

Keep up the good work!

**Comment by htanjo** [comment]
My pleasure!
Good. I will describe how to generate the demo in the next version.

**Comment by jjalonso** [comment]
--css filename.css is not adding anything to me? any clue about it?
